"""
AI Mentor (Milestone 4, Part 12 of the spec).

Every answer is generated by a real LLM call grounded in the learner's
actual recorded evidence (weaknesses, fallacies, presentation scores) and
their recent conversation history — never a canned/hardcoded reply. Falls
back through the configured LLM provider chain (app/services/llm_provider.py)
and finally to a deterministic, evidence-grounded answer if every provider
is unavailable, so the Mentor never 500s or returns an empty reply.
"""
import logging
from datetime import datetime, timezone

from app.core.database import mentor_messages_collection
from app.services.llm_provider import get_text_result_with_history, AllProvidersUnavailableError

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the AI Mentor inside a debate-coaching platform.
Answer the learner's question about debate technique, argument structure,
logical fallacies, rebuttals, vocabulary, or debate formats.

Ground your answer in the learner's real evidence below whenever it's
relevant to their question — reference their actual recent weaknesses or
fallacies by name rather than speaking generically, but don't force it in
if the question is unrelated to their history.

Learner evidence (JSON): {evidence}

Keep answers focused and under 150 words."""


def _deterministic_answer(question: str, evidence: dict) -> str:
    """Grounded, rule-based fallback answer used only if every LLM provider
    is unavailable. Still reacts to the learner's real evidence and question
    instead of returning a canned reply."""
    q_lower = question.lower()
    weaknesses = evidence.get("weaknesses") or []
    fallacies = evidence.get("recent_fallacy_types") or evidence.get("fallacy_types") or []

    topic_answers = {
        "evidence": (
            "Strong evidence means citing a specific source, statistic, or study rather than "
            "a general assertion — for example, 'a 2023 study found X' beats 'many people say X'. "
            "Always link the evidence directly back to your claim with a connector like 'because' "
            "or 'this shows that'."
        ),
        "fallacy": (
            "The most common fallacies to watch for are Ad Hominem (attacking the person instead "
            "of the argument), Slippery Slope (assuming one step leads to an extreme outcome), and "
            "Hasty Generalization (drawing a broad conclusion from limited examples). Naming the "
            "fallacy you spot in an opponent's argument, then explaining the gap, is a strong rebuttal."
        ),
        "rebuttal": (
            "An effective rebuttal directly addresses your opponent's strongest point rather than a "
            "weaker one, questions their evidence or its relevance, and then pivots back to your own "
            "case. Avoid simply restating your original point louder."
        ),
        "structure": (
            "A strong argument follows Claim -> Evidence -> Reasoning -> Impact: state your claim, "
            "back it with evidence, explain the logical link, then explain why it matters to the "
            "debate's outcome."
        ),
    }

    for keyword, answer in topic_answers.items():
        if keyword in q_lower:
            base = answer
            break
    else:
        base = (
            "Great debate technique comes down to three things: back every claim with real evidence, "
            "keep your reasoning chain explicit (don't skip steps), and directly engage with your "
            "opponent's strongest point rather than talking past it."
        )

    grounding = ""
    if weaknesses:
        grounding = f" Based on your recent sessions, one area to focus on is: {weaknesses[0]}."
    elif fallacies:
        grounding = f" You've recently had a '{fallacies[0]}' flagged, so that's worth reviewing."

    return base + grounding


async def ask_mentor(user_id: str, question: str, evidence: dict) -> str:
    history_cursor = mentor_messages_collection.find({"user_id": user_id}).sort("created_at", -1).limit(6)
    history = [doc async for doc in history_cursor]
    history.reverse()

    messages = [("system", SYSTEM_PROMPT)]
    for h in history:
        role = "human" if h["role"] == "user" else "ai"
        messages.append((role, h["text"]))
    messages.append(("human", "{question}"))

    try:
        answer = await get_text_result_with_history(
            messages=messages,
            variables={"evidence": evidence, "question": question},
            temperature=0.4,
        )
    except AllProvidersUnavailableError:
        logger.warning("ask_mentor: all LLM providers unavailable, using deterministic fallback")
        answer = _deterministic_answer(question, evidence)
    except Exception:
        logger.exception("ask_mentor: unexpected error, using deterministic fallback")
        answer = _deterministic_answer(question, evidence)

    now = datetime.now(timezone.utc).isoformat()
    await mentor_messages_collection.insert_many([
        {"user_id": user_id, "role": "user", "text": question, "created_at": now},
        {"user_id": user_id, "role": "mentor", "text": answer, "created_at": now},
    ])
    return answer


async def get_history(user_id: str, limit: int = 30) -> list[dict]:
    cursor = mentor_messages_collection.find({"user_id": user_id}).sort("created_at", 1).limit(limit)
    out = []
    async for doc in cursor:
        doc["id"] = str(doc["_id"])
        out.append(doc)
    return out
