"""
Quiz Engine (Milestone 4, Part 10 of the spec).

Quiz topics are drawn from the fixed pedagogical list in schemas/learning_hub.py
(these categories aren't invented per-learner, but which topics are
*recommended* is computed from real weakness/fallacy history). Questions
inside a topic are freshly generated by an LLM per attempt — never a
hardcoded question bank — and scored server-side so answers can't leak to
the client.
"""
from datetime import datetime

from langchain_core.prompts import ChatPromptTemplate
from bson import ObjectId
from bson.errors import InvalidId

from app.core.database import quiz_attempts_collection
from app.schemas.learning_hub import QuizGenerated, QuizQuestionGenerated, QUIZ_TOPICS
from app.services.llm_provider import get_structured_result, AllProvidersUnavailableError
import logging

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are writing a short debate-skills quiz.
Generate 5 multiple-choice questions on the given topic, each with exactly
4 options and one correct_index (0-3). Questions should test real
understanding, not trivia — appropriate for a debate/communication-skills
learner."""


# Deterministic fallback question bank — used ONLY if every LLM provider is
# unavailable, so quiz generation never 500s or returns an empty quiz. One
# solid, hand-written question per topic is repeated with light variation to
# always produce a full 5-question quiz; this is intentionally a fallback of
# last resort, not the primary content source (that's the LLM above).
_FALLBACK_BANK: dict[str, list[dict]] = {
    "Logical Fallacies": [
        {"question": "Which fallacy attacks the person instead of their argument?", "options": ["Ad Hominem", "Slippery Slope", "Red Herring", "Circular Reasoning"], "correct_index": 0},
        {"question": "A 'false dilemma' fallacy occurs when a speaker:", "options": ["Cites too much evidence", "Presents only two options when more exist", "Repeats their claim twice", "Uses a metaphor"], "correct_index": 1},
        {"question": "Assuming one small step will inevitably lead to an extreme outcome is called:", "options": ["Hasty Generalization", "Appeal to Authority", "Slippery Slope", "Straw Man"], "correct_index": 2},
        {"question": "Drawing a broad conclusion from very few examples is:", "options": ["Hasty Generalization", "Circular Reasoning", "Red Herring", "Ad Hominem"], "correct_index": 0},
        {"question": "Restating a claim as its own justification is called:", "options": ["Appeal to Authority", "Circular Reasoning", "False Dilemma", "Slippery Slope"], "correct_index": 1},
    ],
    "Debate Formats": [
        {"question": "In Oxford-style debate, the motion is:", "options": ["Ignored", "Formally proposed and opposed", "Chosen by the audience mid-debate", "Optional"], "correct_index": 1},
        {"question": "Parliamentary debate commonly uses the term:", "options": ["Prosecution", "The Honorable Member", "Plaintiff", "Witness"], "correct_index": 1},
        {"question": "Policy debate typically focuses heavily on:", "options": ["Poetry", "Plans and counter-plans", "Personal anecdotes only", "Silence"], "correct_index": 1},
        {"question": "Public Forum debate style favors:", "options": ["Dense technical jargon", "Concise, persuasive, accessible arguments", "No rebuttals", "Only statistics"], "correct_index": 1},
        {"question": "A 'group debate' format typically involves:", "options": ["Only one speaker per side", "Multiple teammates each building the team's case", "No opposing side", "Written-only responses"], "correct_index": 1},
    ],
    "Critical Thinking": [
        {"question": "A syllogism is a form of:", "options": ["Emotional appeal", "Logical deduction", "Random guessing", "Storytelling"], "correct_index": 1},
        {"question": "Confirmation bias refers to:", "options": ["Weighing all evidence equally", "Favoring information that confirms existing beliefs", "Always changing your mind", "Ignoring your own arguments"], "correct_index": 1},
        {"question": "A strong counter-argument should:", "options": ["Ignore the opponent's point", "Directly engage the opponent's strongest point", "Only restate your own claim", "Avoid evidence"], "correct_index": 1},
        {"question": "Correlation implying causation without justification is a reasoning error because:", "options": ["Correlation always means causation", "Other factors could explain the relationship", "Causation is irrelevant to debate", "It's actually valid reasoning"], "correct_index": 1},
        {"question": "Steelmanning an argument means:", "options": ["Weakening it before attacking", "Representing it in its strongest form before responding", "Ignoring it", "Repeating it verbatim"], "correct_index": 1},
    ],
    "Argument Structures": [
        {"question": "The standard structure for a strong argument is:", "options": ["Claim -> Evidence -> Reasoning -> Impact", "Evidence only", "Reasoning only", "Impact only"], "correct_index": 0},
        {"question": "A 'warrant' in argumentation refers to:", "options": ["The claim itself", "The logical link connecting evidence to a claim", "An unrelated fact", "The conclusion"], "correct_index": 1},
        {"question": "Framing a debate case around a central thesis helps by:", "options": ["Confusing the audience", "Giving every point a clear, unifying purpose", "Removing the need for evidence", "Making rebuttals harder"], "correct_index": 1},
        {"question": "Case-building means:", "options": ["Only preparing one argument", "Constructing a structured set of interlinked arguments in advance", "Improvising every point live", "Avoiding evidence"], "correct_index": 1},
        {"question": "An 'impact' in debate argumentation explains:", "options": ["Nothing new", "Why the argument matters to the debate's outcome", "The opponent's schedule", "The judge's opinion"], "correct_index": 1},
    ],
    "Public Speaking": [
        {"question": "An ideal speaking pace for clarity is roughly:", "options": ["50-80 words/minute", "130-160 words/minute", "300+ words/minute", "Pace doesn't matter"], "correct_index": 1},
        {"question": "Filler words like 'um' and 'like' primarily hurt:", "options": ["Grammar only", "Perceived confidence and clarity", "Nothing at all", "Only written speech"], "correct_index": 1},
        {"question": "Pausing briefly after a key point helps:", "options": ["Confuse the audience", "Let the point land and land with more weight", "Waste time", "Nothing"], "correct_index": 1},
        {"question": "Vocal variety (pitch/tone changes) mainly improves:", "options": ["Engagement and emphasis", "Grammar", "Word count", "Nothing"], "correct_index": 0},
        {"question": "Eye contact/engagement techniques primarily build:", "options": ["Distance from the audience", "Audience trust and connection", "Confusion", "Nothing measurable"], "correct_index": 1},
    ],
    "Persuasive Speaking": [
        {"question": "Ethos, pathos, and logos refer to appeals based on:", "options": ["Credibility, emotion, and logic", "Volume, speed, and pitch", "Color, sound, and light", "None of these"], "correct_index": 0},
        {"question": "Using a relatable story to support a claim is an appeal to:", "options": ["Logos", "Pathos", "Kairos", "Ethos only"], "correct_index": 1},
        {"question": "Citing your credentials to support a claim is primarily an appeal to:", "options": ["Ethos", "Pathos", "Logos", "None"], "correct_index": 0},
        {"question": "Rhetorical questions are used to:", "options": ["Demand a literal answer", "Provoke reflection and reinforce a point", "Confuse the judge", "End a debate early"], "correct_index": 1},
        {"question": "Repetition of a key phrase in a speech mainly serves to:", "options": ["Waste time", "Reinforce and make the point memorable", "Confuse the audience", "Replace evidence"], "correct_index": 1},
    ],
    "Reasoning": [
        {"question": "Deductive reasoning moves from:", "options": ["Specific examples to a general rule", "General premises to a specific conclusion", "Nowhere to somewhere", "Emotion to logic"], "correct_index": 1},
        {"question": "Inductive reasoning moves from:", "options": ["General premises to a specific conclusion", "Specific observations to a general conclusion", "Nothing to nothing", "Only emotion"], "correct_index": 1},
        {"question": "A valid argument with false premises is:", "options": ["Automatically true", "Logically valid but not necessarily sound", "Impossible", "Always persuasive"], "correct_index": 1},
        {"question": "An enthymeme is:", "options": ["A fully spelled-out syllogism", "A syllogism with an unstated (implied) premise", "A type of fallacy", "An unrelated rhetorical device"], "correct_index": 1},
        {"question": "Non-sequitur means:", "options": ["A conclusion that logically follows", "A conclusion that does NOT logically follow from its premises", "A true statement", "A type of evidence"], "correct_index": 1},
    ],
    "Evidence": [
        {"question": "The strongest evidence for a claim typically includes:", "options": ["Vague opinion", "A specific, cited source or statistic", "Repetition", "Volume"], "correct_index": 1},
        {"question": "Anecdotal evidence is generally considered:", "options": ["The strongest possible evidence", "Weaker than data from a broader, representative sample", "Irrelevant to all debates", "Equal to peer-reviewed research"], "correct_index": 1},
        {"question": "Peer-reviewed research is valued because it:", "options": ["Is always free", "Has been vetted by other experts in the field", "Is always recent", "Requires no citation"], "correct_index": 1},
        {"question": "Citing a source's date matters because:", "options": ["It never matters", "Evidence can become outdated as circumstances change", "Older is always better", "Newer is always false"], "correct_index": 1},
        {"question": "'Correlation is not causation' reminds debaters to:", "options": ["Ignore all statistics", "Verify that a claimed cause actually explains the effect", "Never use data", "Always assume causation"], "correct_index": 1},
    ],
}


def _fallback_quiz(topic: str) -> QuizGenerated:
    bank = _FALLBACK_BANK.get(topic) or _FALLBACK_BANK["Critical Thinking"]
    return QuizGenerated(questions=[QuizQuestionGenerated(**q) for q in bank])


def recommend_topics(weakness_keywords: list[str], past_attempts: dict[str, list[dict]]) -> list[dict]:
    """Rule-based (not LLM) match of the fixed topic list against real
    detected weaknesses/fallacies, plus real past-attempt history."""
    keyword_map = {
        "Logical Fallacies": ["fallacy", "straw man", "ad hominem", "false dilemma", "slippery slope"],
        "Debate Formats": ["format", "structure", "parliamentary", "oxford", "policy"],
        "Critical Thinking": ["reasoning", "logic", "critical", "analysis"],
        "Argument Structures": ["structure", "framing", "thesis", "case building"],
        "Public Speaking": ["clarity", "pace", "confidence", "delivery", "filler"],
        "Persuasive Speaking": ["persuasion", "emotion", "rhetoric"],
        "Reasoning": ["reasoning", "logic", "inference"],
        "Evidence": ["evidence", "citation", "statistic", "source", "data"],
    }
    combined_text = " ".join(weakness_keywords).lower()

    out = []
    for topic in QUIZ_TOPICS:
        matched = any(kw in combined_text for kw in keyword_map.get(topic, []))
        attempts = past_attempts.get(topic, [])
        scored = [a["score"] for a in attempts if a.get("score") is not None]
        last_score = scored[-1] if scored else None
        out.append({
            "topic": topic,
            "recommended": matched or (last_score is not None and last_score < 70),
            "reason": "Matches a weakness or fallacy in your recent debates" if matched else None,
            "last_score": last_score,
            "attempts": len(attempts),
        })
    return out


async def start_quiz(user_id: str, topic: str) -> dict:
    try:
        result = await get_structured_result(
            system_prompt=SYSTEM_PROMPT,
            human_prompt="Topic: {topic}",
            variables={"topic": topic},
            output_schema=QuizGenerated,
            temperature=0.5,
        )
    except AllProvidersUnavailableError:
        logger.warning("start_quiz: all LLM providers unavailable, using deterministic fallback bank")
        result = _fallback_quiz(topic)
    except Exception:
        logger.exception("start_quiz: unexpected error, using deterministic fallback bank")
        result = _fallback_quiz(topic)

    now = datetime.utcnow().isoformat()
    doc = {
        "user_id": user_id,
        "topic": topic,
        "questions": [q.model_dump() for q in result.questions],
        "score": None,
        "completed": False,
        "created_at": now,
    }
    insert_result = await quiz_attempts_collection.insert_one(doc)
    doc["id"] = str(insert_result.inserted_id)
    return doc


async def get_attempt(user_id: str, attempt_id: str) -> dict | None:
    try:
        oid = ObjectId(attempt_id)
    except InvalidId:
        return None
    doc = await quiz_attempts_collection.find_one({"_id": oid})
    if not doc or doc["user_id"] != user_id:
        return None
    doc["id"] = str(doc["_id"])
    return doc


async def submit_attempt(user_id: str, attempt_id: str, answers: list[int]) -> dict | None:
    doc = await get_attempt(user_id, attempt_id)
    if not doc:
        return None
    questions = doc["questions"]
    correct = sum(1 for q, a in zip(questions, answers) if a == q["correct_index"])
    score = round((correct / len(questions)) * 100, 2) if questions else 0.0

    await quiz_attempts_collection.update_one(
        {"_id": ObjectId(attempt_id)},
        {"$set": {"score": score, "completed": True, "submitted_at": datetime.utcnow().isoformat()}},
    )
    doc["score"] = score
    doc["completed"] = True
    return doc


async def list_history(user_id: str) -> dict[str, list[dict]]:
    """Groups all past attempts by topic — used both for recommendation
    scoring and for exposing real quiz history to learner analytics."""
    out: dict[str, list[dict]] = {t: [] for t in QUIZ_TOPICS}
    cursor = quiz_attempts_collection.find({"user_id": user_id, "completed": True}).sort("created_at", 1)
    async for doc in cursor:
        out.setdefault(doc["topic"], []).append({"score": doc.get("score"), "created_at": doc["created_at"]})
    return out
