import { useEffect, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { FaArrowRight, FaChartLine, FaClipboardCheck, FaPlus, FaSyncAlt, FaUsers } from "react-icons/fa";
import Sidebar from "./Sidebar";
import ChatBot from "./chatbot/ChatBot";
import api from "../services/api";

const labels = {
  coach: { learners: "Learners", "assigned-debates": "Assigned Debates", sessions: "Debate Sessions", evaluations: "AI Evaluation Queue", arguments: "Argument Reviews", fallacies: "Fallacy Reports", presentations: "Presentation Reviews", plans: "Coaching Plans", analytics: "Performance Analytics", reports: "Reports", messages: "Messages", notifications: "Notifications" },
  educator: { progress: "Class Progress", students: "Students", topics: "Debate Topics", sessions: "Practice Sessions", assignments: "Assignments", performance: "Performance Scores", reports: "Class Reports", resources: "Learning Resources", notifications: "Notifications" },
  admin: { users: "User Management", roles: "Role & Permissions", analytics: "System Analytics", sessions: "Debate Sessions", "ai-services": "AI Models & Services", content: "Content Management", reports: "Reports & Logs", billing: "Subscriptions & Billing", notifications: "Notification Center", settings: "System Settings", security: "Security & Compliance", integrations: "Integrations", backup: "Backup & Recovery" },
};

export default function WorkspaceSection({ role, base }) {
  const { section } = useParams(); const navigate = useNavigate(); const title = labels[base][section] || "Workspace";
  const [items, setItems] = useState([]); const [loading, setLoading] = useState(true); const [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); try { const { data } = await api.get("/analysis/history"); setItems(data || []); } catch { setItems([]); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [section]);
  const action = () => setNotice(`${title} action started. Select an item below to continue.`);
  return <div className="min-h-screen bg-[#f8f9fd] flex"><Sidebar/><main className="min-w-0 flex-1"><header className="flex min-h-20 items-center justify-between border-b border-slate-100 bg-white px-6"><div><p className="text-xs font-bold tracking-widest text-violet-600">{role.toUpperCase()} WORKSPACE</p><h1 className="mt-1 text-xl font-bold text-slate-900">{title}</h1></div><Link to={`/${base}`} className="text-sm font-semibold text-violet-600">← Dashboard</Link></header><div className="mx-auto max-w-7xl p-6">{notice && <div className="mb-4 rounded-xl bg-violet-50 p-3 text-sm text-violet-700">{notice}</div>}<section className="rounded-2xl bg-gradient-to-r from-[#111b38] to-violet-800 p-7 text-white"><h2 className="text-2xl font-bold">{title}</h2><p className="mt-2 text-sm text-violet-100">Manage this area of your DebateForge workspace and use live learner analysis data to guide your next action.</p><button onClick={action} className="mt-5 inline-flex items-center gap-2 rounded-lg bg-white px-4 py-2.5 text-sm font-bold text-slate-800"><FaPlus/> Create or manage</button></section><section className="mt-5 grid gap-5 lg:grid-cols-3"><article className="rounded-xl bg-white p-5 shadow-sm"><FaUsers className="text-2xl text-violet-600"/><p className="mt-4 text-3xl font-bold">{items.length}</p><p className="text-sm text-slate-500">Available analysis records</p></article><article className="rounded-xl bg-white p-5 shadow-sm"><FaClipboardCheck className="text-2xl text-violet-600"/><p className="mt-4 text-3xl font-bold">{Math.max(0, items.length - 1)}</p><p className="text-sm text-slate-500">Items ready to review</p></article><article className="rounded-xl bg-white p-5 shadow-sm"><FaChartLine className="text-2xl text-violet-600"/><p className="mt-4 text-3xl font-bold">Live</p><p className="text-sm text-slate-500">Data refreshed on demand</p></article></section><section className="mt-5 rounded-xl bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h2 className="font-bold">Relevant activity</h2><button onClick={load} className="inline-flex items-center gap-2 text-sm font-semibold text-violet-600"><FaSyncAlt className={loading ? "animate-spin" : ""}/>Refresh</button></div><div className="space-y-2">{items.slice(0,6).map((item) => <button key={item.id} onClick={() => navigate(`/learner/report/${item.id}`)} className="flex w-full items-center justify-between rounded-lg border border-slate-100 p-3 text-left hover:bg-violet-50"><span className="max-w-[75%] truncate text-sm font-medium">{item.argument}</span><span className="inline-flex items-center gap-2 text-xs font-bold text-violet-600">{item.overall_score}/10 <FaArrowRight/></span></button>)}{!items.length && !loading && <p className="py-8 text-center text-sm text-slate-500">No activity is available yet.</p>}</div></section></div><ChatBot/></main></div>;
}
