"""
Debate Processing Schemas

Purpose:
    Defines the request and response models for the complete
    debate processing workflow.

Responsibilities:
    - Standardize the final debate analysis response.
    - Aggregate outputs from Speech and AI modules.
    - Provide a single response contract for the frontend.

Supported Input Methods:
    - Live Speech Recording
    - Audio Upload
    - Video Upload

Note:
    This schema belongs to the Debate Module and acts as the
    contract between the backend and frontend.
"""

from pydantic import BaseModel, Field

from app.ai.schemas.argument_analysis_schema import (
    ArgumentAnalysisResponse,
)
from app.ai.schemas.counterargument_schema import (
    CounterargumentResponse,
)
from app.ai.schemas.fallacy_detection_schema import (
    FallacyDetectionResponse,
)


class DebateTranscription(BaseModel):
    """
    Speech transcription generated from the uploaded
    audio/video or live recording.
    """

    transcript: str = Field(
        ...,
        description="Speech transcript generated by Whisper."
    )


class DebateAnalysisData(BaseModel):
    """
    Complete debate analysis generated for one debate turn.
    """

    session_id: int

    transcript: DebateTranscription

    argument_analysis: ArgumentAnalysisResponse

    counterargument_analysis: CounterargumentResponse

    logical_fallacy_analysis: FallacyDetectionResponse


class DebateAnalysisResponse(BaseModel):
    """
    Final response returned after complete debate processing.
    """

    success: bool

    message: str

    data: DebateAnalysisData