from app.database.database import SessionLocal
from app.models.debate import DebateTopic

db = SessionLocal()

topics = [
    {
        "title": "Should Artificial Intelligence Replace Teachers?",
        "description": "Debate on: Should Artificial Intelligence Replace Teachers?",
        "difficulty": "Easy",
        "category": "Technology",
    },
    {
        "title": "Is ChatGPT Helping Students Learn?",
        "description": "Debate on: Is ChatGPT Helping Students Learn?",
        "difficulty": "Easy",
        "category": "Technology",
    },
    {
        "title": "Should Social Media Be Regulated?",
        "description": "Debate on: Should Social Media Be Regulated?",
        "difficulty": "Easy",
        "category": "Technology",
    },
    {
        "title": "Are Smartphones Making People Less Social?",
        "description": "Debate on: Are Smartphones Making People Less Social?",
        "difficulty": "Easy",
        "category": "Technology",
    },
    {
        "title": "Should Coding Be Mandatory in Schools?",
        "description": "Debate on: Should Coding Be Mandatory in Schools?",
        "difficulty": "Easy",
        "category": "Technology",
    },
    {
        "title": "Is Artificial Intelligence Dangerous?",
        "description": "Debate on: Is Artificial Intelligence Dangerous?",
        "difficulty": "Medium",
        "category": "Technology",
    },
    {
        "title": "Should Autonomous Cars Replace Human Drivers?",
        "description": "Debate on: Should Autonomous Cars Replace Human Drivers?",
        "difficulty": "Medium",
        "category": "Technology",
    },
    {
        "title": "Should Cryptocurrency Replace Cash?",
        "description": "Debate on: Should Cryptocurrency Replace Cash?",
        "difficulty": "Medium",
        "category": "Technology",
    },
    {
        "title": "Should Facial Recognition Be Banned?",
        "description": "Debate on: Should Facial Recognition Be Banned?",
        "difficulty": "Medium",
        "category": "Technology",
    },
    {
        "title": "Should Internet Access Be a Basic Human Right?",
        "description": "Debate on: Should Internet Access Be a Basic Human Right?",
        "difficulty": "Medium",
        "category": "Technology",
    },
    {
        "title": "Should Robots Replace Human Workers?",
        "description": "Debate on: Should Robots Replace Human Workers?",
        "difficulty": "Hard",
        "category": "Technology",
    },
    {
        "title": "Should Data Privacy Laws Be Stronger?",
        "description": "Debate on: Should Data Privacy Laws Be Stronger?",
        "difficulty": "Hard",
        "category": "Technology",
    },
    {
        "title": "Is Virtual Reality the Future of Education?",
        "description": "Debate on: Is Virtual Reality the Future of Education?",
        "difficulty": "Hard",
        "category": "Technology",
    },
    {
        "title": "Should Space Exploration Receive More Funding?",
        "description": "Debate on: Should Space Exploration Receive More Funding?",
        "difficulty": "Hard",
        "category": "Technology",
    },
    {
        "title": "Should Online Learning Replace Traditional Learning?",
        "description": "Debate on: Should Online Learning Replace Traditional Learning?",
        "difficulty": "Hard",
        "category": "Technology",
    },
    {
        "title": "Should Healthcare Be Free?",
        "description": "Debate on: Should Healthcare Be Free?",
        "difficulty": "Easy",
        "category": "Healthcare",
    },
    {
        "title": "Should Vaccination Be Mandatory?",
        "description": "Debate on: Should Vaccination Be Mandatory?",
        "difficulty": "Easy",
        "category": "Healthcare",
    },
    {
        "title": "Is Telemedicine Better Than Traditional Healthcare?",
        "description": "Debate on: Is Telemedicine Better Than Traditional Healthcare?",
        "difficulty": "Easy",
        "category": "Healthcare",
    },
    {
        "title": "Should Organ Donation Be Mandatory?",
        "description": "Debate on: Should Organ Donation Be Mandatory?",
        "difficulty": "Easy",
        "category": "Healthcare",
    },
    {
        "title": "Should Junk Food Advertising Be Banned?",
        "description": "Debate on: Should Junk Food Advertising Be Banned?",
        "difficulty": "Easy",
        "category": "Healthcare",
    },
    {
        "title": "Is Mental Health Education Necessary?",
        "description": "Debate on: Is Mental Health Education Necessary?",
        "difficulty": "Medium",
        "category": "Healthcare",
    },
    {
        "title": "Should Sugar Be Taxed?",
        "description": "Debate on: Should Sugar Be Taxed?",
        "difficulty": "Medium",
        "category": "Healthcare",
    },
    {
        "title": "Should Euthanasia Be Legalized?",
        "description": "Debate on: Should Euthanasia Be Legalized?",
        "difficulty": "Medium",
        "category": "Healthcare",
    },
    {
        "title": "Should Genetic Engineering Be Allowed?",
        "description": "Debate on: Should Genetic Engineering Be Allowed?",
        "difficulty": "Medium",
        "category": "Healthcare",
    },
    {
        "title": "Can AI Improve Healthcare?",
        "description": "Debate on: Can AI Improve Healthcare?",
        "difficulty": "Medium",
        "category": "Healthcare",
    },
    {
        "title": "Should Hospitals Be Privatized?",
        "description": "Debate on: Should Hospitals Be Privatized?",
        "difficulty": "Hard",
        "category": "Healthcare",
    },
    {
        "title": "Should Fitness Tracking Be Mandatory?",
        "description": "Debate on: Should Fitness Tracking Be Mandatory?",
        "difficulty": "Hard",
        "category": "Healthcare",
    },
    {
        "title": "Is Preventive Healthcare Better Than Treatment?",
        "description": "Debate on: Is Preventive Healthcare Better Than Treatment?",
        "difficulty": "Hard",
        "category": "Healthcare",
    },
    {
        "title": "Should Medical Data Be Shared for Research?",
        "description": "Debate on: Should Medical Data Be Shared for Research?",
        "difficulty": "Hard",
        "category": "Healthcare",
    },
    {
        "title": "Should Schools Conduct Annual Health Screenings?",
        "description": "Debate on: Should Schools Conduct Annual Health Screenings?",
        "difficulty": "Hard",
        "category": "Healthcare",
    },
    {
        "title": "Should Homework Be Banned?",
        "description": "Debate on: Should Homework Be Banned?",
        "difficulty": "Easy",
        "category": "Education",
    },
    {
        "title": "Should Exams Be Abolished?",
        "description": "Debate on: Should Exams Be Abolished?",
        "difficulty": "Easy",
        "category": "Education",
    },
    {
        "title": "Should School Uniforms Be Mandatory?",
        "description": "Debate on: Should School Uniforms Be Mandatory?",
        "difficulty": "Easy",
        "category": "Education",
    },
    {
        "title": "Should Financial Literacy Be Compulsory?",
        "description": "Debate on: Should Financial Literacy Be Compulsory?",
        "difficulty": "Easy",
        "category": "Education",
    },
    {
        "title": "Should Attendance Be Optional?",
        "description": "Debate on: Should Attendance Be Optional?",
        "difficulty": "Easy",
        "category": "Education",
    },
    {
        "title": "Should Students Use AI Tools?",
        "description": "Debate on: Should Students Use AI Tools?",
        "difficulty": "Medium",
        "category": "Education",
    },
    {
        "title": "Are Grades the Best Measure of Intelligence?",
        "description": "Debate on: Are Grades the Best Measure of Intelligence?",
        "difficulty": "Medium",
        "category": "Education",
    },
    {
        "title": "Should Coding Start in Primary School?",
        "description": "Debate on: Should Coding Start in Primary School?",
        "difficulty": "Medium",
        "category": "Education",
    },
    {
        "title": "Should Colleges Remove Entrance Exams?",
        "description": "Debate on: Should Colleges Remove Entrance Exams?",
        "difficulty": "Medium",
        "category": "Education",
    },
    {
        "title": "Should Practical Learning Replace Theory?",
        "description": "Debate on: Should Practical Learning Replace Theory?",
        "difficulty": "Medium",
        "category": "Education",
    },
    {
        "title": "Should Students Choose Their Subjects?",
        "description": "Debate on: Should Students Choose Their Subjects?",
        "difficulty": "Hard",
        "category": "Education",
    },
    {
        "title": "Is Online Education Better?",
        "description": "Debate on: Is Online Education Better?",
        "difficulty": "Hard",
        "category": "Education",
    },
    {
        "title": "Should Internships Be Mandatory?",
        "description": "Debate on: Should Internships Be Mandatory?",
        "difficulty": "Hard",
        "category": "Education",
    },
    {
        "title": "Should Schools Teach Entrepreneurship?",
        "description": "Debate on: Should Schools Teach Entrepreneurship?",
        "difficulty": "Hard",
        "category": "Education",
    },
    {
        "title": "Should Mobile Phones Be Allowed in Class?",
        "description": "Debate on: Should Mobile Phones Be Allowed in Class?",
        "difficulty": "Hard",
        "category": "Education",
    },
    {
        "title": "Should Plastic Be Completely Banned?",
        "description": "Debate on: Should Plastic Be Completely Banned?",
        "difficulty": "Easy",
        "category": "Environment",
    },
    {
        "title": "Should Electric Vehicles Replace Petrol Vehicles?",
        "description": "Debate on: Should Electric Vehicles Replace Petrol Vehicles?",
        "difficulty": "Easy",
        "category": "Environment",
    },
    {
        "title": "Is Nuclear Energy Better Than Fossil Fuels?",
        "description": "Debate on: Is Nuclear Energy Better Than Fossil Fuels?",
        "difficulty": "Easy",
        "category": "Environment",
    },
    {
        "title": "Should Water Usage Be Restricted?",
        "description": "Debate on: Should Water Usage Be Restricted?",
        "difficulty": "Easy",
        "category": "Environment",
    },
    {
        "title": "Should Governments Plant More Trees?",
        "description": "Debate on: Should Governments Plant More Trees?",
        "difficulty": "Easy",
        "category": "Environment",
    },
    {
        "title": "Is Climate Change Reversible?",
        "description": "Debate on: Is Climate Change Reversible?",
        "difficulty": "Medium",
        "category": "Environment",
    },
    {
        "title": "Should Fast Fashion Be Banned?",
        "description": "Debate on: Should Fast Fashion Be Banned?",
        "difficulty": "Medium",
        "category": "Environment",
    },
    {
        "title": "Should Recycling Be Mandatory?",
        "description": "Debate on: Should Recycling Be Mandatory?",
        "difficulty": "Medium",
        "category": "Environment",
    },
    {
        "title": "Are Zoos Ethical?",
        "description": "Debate on: Are Zoos Ethical?",
        "difficulty": "Medium",
        "category": "Environment",
    },
    {
        "title": "Should Countries Ban Single-Use Plastics?",
        "description": "Debate on: Should Countries Ban Single-Use Plastics?",
        "difficulty": "Medium",
        "category": "Environment",
    },
    {
        "title": "Should Carbon Taxes Be Increased?",
        "description": "Debate on: Should Carbon Taxes Be Increased?",
        "difficulty": "Hard",
        "category": "Environment",
    },
    {
        "title": "Should Wildlife Protection Be Prioritized?",
        "description": "Debate on: Should Wildlife Protection Be Prioritized?",
        "difficulty": "Hard",
        "category": "Environment",
    },
    {
        "title": "Should Rainwater Harvesting Be Mandatory?",
        "description": "Debate on: Should Rainwater Harvesting Be Mandatory?",
        "difficulty": "Hard",
        "category": "Environment",
    },
    {
        "title": "Should Green Buildings Be Compulsory?",
        "description": "Debate on: Should Green Buildings Be Compulsory?",
        "difficulty": "Hard",
        "category": "Environment",
    },
    {
        "title": "Should Renewable Energy Receive More Funding?",
        "description": "Debate on: Should Renewable Energy Receive More Funding?",
        "difficulty": "Hard",
        "category": "Environment",
    },
    {
        "title": "Should Companies Adopt a Four-Day Work Week?",
        "description": "Debate on: Should Companies Adopt a Four-Day Work Week?",
        "difficulty": "Easy",
        "category": "Business",
    },
    {
        "title": "Should CEOs Have Salary Limits?",
        "description": "Debate on: Should CEOs Have Salary Limits?",
        "difficulty": "Easy",
        "category": "Business",
    },
    {
        "title": "Is Remote Work Better Than Office Work?",
        "description": "Debate on: Is Remote Work Better Than Office Work?",
        "difficulty": "Easy",
        "category": "Business",
    },
    {
        "title": "Should Unpaid Internships Be Banned?",
        "description": "Debate on: Should Unpaid Internships Be Banned?",
        "difficulty": "Easy",
        "category": "Business",
    },
    {
        "title": "Should Companies Reveal Employee Salaries?",
        "description": "Debate on: Should Companies Reveal Employee Salaries?",
        "difficulty": "Easy",
        "category": "Business",
    },
    {
        "title": "Should AI Replace Customer Support?",
        "description": "Debate on: Should AI Replace Customer Support?",
        "difficulty": "Medium",
        "category": "Business",
    },
    {
        "title": "Should Businesses Prioritize Sustainability?",
        "description": "Debate on: Should Businesses Prioritize Sustainability?",
        "difficulty": "Medium",
        "category": "Business",
    },
    {
        "title": "Should Employees Get Unlimited Leave?",
        "description": "Debate on: Should Employees Get Unlimited Leave?",
        "difficulty": "Medium",
        "category": "Business",
    },
    {
        "title": "Is Entrepreneurship Better Than Employment?",
        "description": "Debate on: Is Entrepreneurship Better Than Employment?",
        "difficulty": "Medium",
        "category": "Business",
    },
    {
        "title": "Should Work-Life Balance Be Prioritized?",
        "description": "Debate on: Should Work-Life Balance Be Prioritized?",
        "difficulty": "Medium",
        "category": "Business",
    },
    {
        "title": "Should Startups Receive Government Support?",
        "description": "Debate on: Should Startups Receive Government Support?",
        "difficulty": "Hard",
        "category": "Business",
    },
    {
        "title": "Should Companies Monitor Employees?",
        "description": "Debate on: Should Companies Monitor Employees?",
        "difficulty": "Hard",
        "category": "Business",
    },
    {
        "title": "Should Advertising to Children Be Restricted?",
        "description": "Debate on: Should Advertising to Children Be Restricted?",
        "difficulty": "Hard",
        "category": "Business",
    },
    {
        "title": "Should Businesses Go Fully Digital?",
        "description": "Debate on: Should Businesses Go Fully Digital?",
        "difficulty": "Hard",
        "category": "Business",
    },
    {
        "title": "Should Freelancing Replace Traditional Jobs?",
        "description": "Debate on: Should Freelancing Replace Traditional Jobs?",
        "difficulty": "Hard",
        "category": "Business",
    },
    {
        "title": "Should Voting Be Compulsory?",
        "description": "Debate on: Should Voting Be Compulsory?",
        "difficulty": "Easy",
        "category": "Politics",
    },
    {
        "title": "Should the Voting Age Be Reduced to 16?",
        "description": "Debate on: Should the Voting Age Be Reduced to 16?",
        "difficulty": "Easy",
        "category": "Politics",
    },
    {
        "title": "Should Governments Regulate Social Media?",
        "description": "Debate on: Should Governments Regulate Social Media?",
        "difficulty": "Easy",
        "category": "Politics",
    },
    {
        "title": "Should Universal Basic Income Be Introduced?",
        "description": "Debate on: Should Universal Basic Income Be Introduced?",
        "difficulty": "Easy",
        "category": "Politics",
    },
    {
        "title": "Should Political Donations Be Public?",
        "description": "Debate on: Should Political Donations Be Public?",
        "difficulty": "Easy",
        "category": "Politics",
    },
    {
        "title": "Is Democracy the Best Form of Government?",
        "description": "Debate on: Is Democracy the Best Form of Government?",
        "difficulty": "Medium",
        "category": "Politics",
    },
    {
        "title": "Should Internet Access Be a Constitutional Right?",
        "description": "Debate on: Should Internet Access Be a Constitutional Right?",
        "difficulty": "Medium",
        "category": "Politics",
    },
    {
        "title": "Should Governments Use AI for Policymaking?",
        "description": "Debate on: Should Governments Use AI for Policymaking?",
        "difficulty": "Medium",
        "category": "Politics",
    },
    {
        "title": "Should Election Campaign Spending Be Limited?",
        "description": "Debate on: Should Election Campaign Spending Be Limited?",
        "difficulty": "Medium",
        "category": "Politics",
    },
    {
        "title": "Should Prison Systems Focus on Rehabilitation?",
        "description": "Debate on: Should Prison Systems Focus on Rehabilitation?",
        "difficulty": "Medium",
        "category": "Politics",
    },
    {
        "title": "Should Capital Punishment Be Abolished?",
        "description": "Debate on: Should Capital Punishment Be Abolished?",
        "difficulty": "Hard",
        "category": "Politics",
    },
    {
        "title": "Should National Service Be Mandatory?",
        "description": "Debate on: Should National Service Be Mandatory?",
        "difficulty": "Hard",
        "category": "Politics",
    },
    {
        "title": "Should Governments Ban Fake News?",
        "description": "Debate on: Should Governments Ban Fake News?",
        "difficulty": "Hard",
        "category": "Politics",
    },
    {
        "title": "Should Borders Be More Open?",
        "description": "Debate on: Should Borders Be More Open?",
        "difficulty": "Hard",
        "category": "Politics",
    },
    {
        "title": "Should Public Transport Be Free?",
        "description": "Debate on: Should Public Transport Be Free?",
        "difficulty": "Hard",
        "category": "Politics",
    },
]

for topic in topics:
    exists = db.query(DebateTopic).filter(DebateTopic.title == topic["title"]).first()
    if not exists:
        db.add(DebateTopic(**topic))

db.commit()
db.close()

print(f"Inserted {len(topics)} debate topics successfully.")
