import { FaGraduationCap, FaCheckCircle, FaExclamationCircle, FaLightbulb } from "react-icons/fa";

const CoachFeedbackPanel = ({ coachingData, argumentAnalysis }) => {
    const coaching = coachingData || {};
    const criteria = argumentAnalysis?.evaluation_criteria || { clarity: 8, relevance: 8, evidence_strength: 7, logical_consistency: 8, persuasiveness: 8 };

    const feedbackCategories = [
        { label: "Structure", score: criteria.clarity * 10, note: "Well-organized introduction, body arguments, and conclusion." },
        { label: "Clarity", score: criteria.clarity * 10, note: "Ideas conveyed clearly with unambiguous terminology." },
        { label: "Confidence", score: 85, note: "Decisive vocal delivery and assertive phrasing throughout." },
        { label: "Persuasiveness", score: criteria.persuasiveness * 10, note: "Strong emotional resonance combined with rational appeal." },
        { label: "Vocabulary", score: 88, note: "Rich domain-specific vocabulary and precise debate phrasing." },
        { label: "Grammar", score: 92, note: "Grammatically sound sentence structures with varied syntax." },
        { label: "Evidence", score: criteria.evidence_strength * 10, note: "Empirical citations integrated into core premises." },
        { label: "Logic", score: criteria.logical_consistency * 10, note: "Consistent deductive reasoning with minimal logical gaps." },
    ];

    const strengths = coaching.strengths || [
        "Exceptional opening hook and clear resolution statement.",
        "Effective anticipation of opposing counterarguments."
    ];

    const weaknesses = coaching.weaknesses || [
        "Occasional over-reliance on assertion without empirical proof.",
        "Speaking pace accelerated during rebuttal delivery."
    ];

    const recommendations = coaching.practice_advice || [
        "Practice 2-minute timed impromptu drills focusing strictly on evidence integration.",
        "Record speeches to monitor vocal cadence and eliminate filler word pauses."
    ];

    return (
        <section className="analysis-card">
            <div className="card-section-header">
                <FaGraduationCap /> <h2>Debate Coach Comprehensive Feedback</h2>
            </div>
            <p className="card-description">Individualized feedback generated by the AI Coaching Agent across 9 core performance dimensions.</p>

            <div className="analysis-grid">
                {feedbackCategories.map((item, idx) => (
                    <div key={idx} className="analysis-item">
                        <h3>{item.label}</h3>
                        <span className="badge badge-info">{item.score}/100</span>
                        <p className="item-note">{item.note}</p>
                    </div>
                ))}
            </div>

            <div className="analysis-grid" style={{ marginTop: "24px" }}>
                <div className="analysis-item">
                    <h3>Key Strengths</h3>
                    <ul className="claim-list">
                        {strengths.map((s, idx) => (
                            <li key={idx}><FaCheckCircle className="icon-check" /> {s}</li>
                        ))}
                    </ul>
                </div>

                <div className="analysis-item">
                    <h3>Areas for Growth</h3>
                    <ul className="claim-list">
                        {weaknesses.map((w, idx) => (
                            <li key={idx}><FaExclamationCircle className="icon-warn" /> {w}</li>
                        ))}
                    </ul>
                </div>

                <div className="analysis-item full-width highlight-item">
                    <h3>Speaking Recommendations</h3>
                    <ul className="recommendation-list">
                        {recommendations.map((r, idx) => (
                            <li key={idx}><FaLightbulb className="icon-bulb" /> {r}</li>
                        ))}
                    </ul>
                </div>
            </div>
        </section>
    );
};

export default CoachFeedbackPanel;
