import { useState } from "react";
import { FaShieldAlt, FaChevronDown, FaChevronUp, FaQuestionCircle, FaBookOpen } from "react-icons/fa";

const CounterargumentPanel = ({ counterargumentData }) => {
    const data = counterargumentData || {};
    const [expandedRebuttal, setExpandedRebuttal] = useState(null);

    const rebuttals = [
        {
            id: "logical",
            title: "Logical Rebuttal",
            content: data.logical_rebuttal || "Challenge the internal premise and logical deduction of the argument.",
            expandedDetail: "Examine whether the conclusion necessarily follows from the premises. If the relationship is contingent rather than necessary, highlight the possibility of alternative outcomes under identical initial conditions.",
            strengthScore: 88,
        },
        {
            id: "evidence",
            title: "Evidence Rebuttal",
            content: data.evidence_rebuttal || "Dispute empirical data sources, sample sizes, and statistical correlations.",
            expandedDetail: "Question sample selection bias, time-horizon limitations of the cited data, and whether correlation has been improperly equated with causation in the supporting studies.",
            strengthScore: 92,
        },
        {
            id: "ethical",
            title: "Ethical Rebuttal",
            content: data.ethical_rebuttal || "Highlight moral implications, stakeholder harms, and distributional equity.",
            expandedDetail: "Evaluate how marginalized stakeholders are impacted. Contrast deontological rights principles against utilitarian net-benefit calculations to reveal ethical friction.",
            strengthScore: 85,
        },
        {
            id: "practical",
            title: "Practical / Policy Rebuttal",
            content: data.practical_or_policy_rebuttal || data.practical_rebuttal || "Analyze implementation bottlenecks, budget constraints, and enforcement challenges.",
            expandedDetail: "Deconstruct bureaucratic overhead, administrative complexity, unintended secondary consequences, and ongoing compliance costs required for sustained execution.",
            strengthScore: 90,
        },
    ];

    const toggleExpand = (id) => {
        setExpandedRebuttal(expandedRebuttal === id ? null : id);
    };

    return (
        <section className="analysis-card">
            <div className="card-section-header">
                <FaShieldAlt /> <h2>AI Counterargument & Rebuttal Generator</h2>
            </div>
            <p className="card-description">Multi-perspective counterarguments generated by the Counterargument Agent with expandable rebuttal strategies.</p>

            <div className="rebuttals-container">
                {rebuttals.map((item) => {
                    const isExpanded = expandedRebuttal === item.id;

                    return (
                        <div key={item.id} className="rebuttal-card">
                            <div className="rebuttal-header" onClick={() => toggleExpand(item.id)}>
                                <div>
                                    <h3>{item.title}</h3>
                                    <span className="badge badge-info">Strength: {item.strengthScore}/100</span>
                                </div>
                                <button type="button" className="btn-icon">
                                    {isExpanded ? <FaChevronUp /> : <FaChevronDown />}
                                </button>
                            </div>
                            <p className="rebuttal-content">{item.content}</p>
                            {isExpanded && (
                                <div className="rebuttal-detail-panel">
                                    <h4>In-Depth Strategic Guidance</h4>
                                    <p>{item.expandedDetail}</p>
                                </div>
                            )}
                        </div>
                    );
                })}
            </div>

            {data.challenge_questions && data.challenge_questions.length > 0 && (
                <div className="analysis-grid" style={{ marginTop: "24px" }}>
                    <div className="analysis-item full-width highlight-item">
                        <h3><FaQuestionCircle /> Strategic Challenge Questions</h3>
                        <ul className="recommendation-list">
                            {data.challenge_questions.map((q, idx) => (
                                <li key={idx}>{q}</li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}

            {data.evidence_sources && data.evidence_sources.length > 0 && (
                <div className="analysis-grid" style={{ marginTop: "16px" }}>
                    <div className="analysis-item full-width">
                        <h3><FaBookOpen /> Knowledge Base Sources</h3>
                        <ul className="recommendation-list">
                            {data.evidence_sources.map((src, idx) => (
                                <li key={idx}><strong>{src.source}:</strong> {src.content}</li>
                            ))}
                        </ul>
                    </div>
                </div>
            )}
        </section>
    );
};

export default CounterargumentPanel;
